# Generated by Django 2.2.1 on 2019-05-24 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='user/%Y-%m', verbose_name='医生的头像')),
                ('IDCard', models.CharField(max_length=32, null=True, unique=True, verbose_name='用户身份证')),
                ('realName', models.CharField(max_length=32, null=True, verbose_name='用户的真实姓名')),
                ('birtyday', models.DateField(null=True, verbose_name='出生年月')),
                ('phone', models.CharField(max_length=13, null=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='通讯地址')),
                ('hospital', models.CharField(max_length=64, null=True, verbose_name='所属医院名称')),
                ('hospitalID', models.IntegerField(null=True, verbose_name='所属医院的ID')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='所属科室名称')),
                ('departemntID', models.IntegerField(null=True, verbose_name='所属科室ID')),
                ('jobLevel', models.CharField(max_length=32, null=True, verbose_name='职称等级')),
                ('college', models.CharField(max_length=64, null=True, verbose_name='毕业院校')),
                ('personalDescription', models.TextField(null=True, verbose_name='个人介绍')),
                ('remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
